# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Monte Carlo Integration in C++
#'
#' This function estimates the integral of a given function using the Monte Carlo method in C++.
#' @param f A function to integrate.
#' @param a Lower limit of integration.
#' @param b Upper limit of integration.
#' @param n Number of random samples.
#' @return Estimated value of the integral.
#' @export
monte_carlo_integrate_cpp <- function(f, a, b, n) {
    .Call(`_MCPackage_monte_carlo_integrate_cpp`, f, a, b, n)
}

